<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'crear_cita' => [[], ['_controller' => 'App\\Controller\\CitaController::crearCita'], [], [['text', '/citas']], [], []],
    'borrar_cita' => [['id'], ['_controller' => 'App\\Controller\\CitaController::borrarCita'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/citas']], [], []],
    'actualizar_cita' => [['id'], ['_controller' => 'App\\Controller\\CitaController::actualizarCita'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/citas']], [], []],
    'get_citas' => [[], ['_controller' => 'App\\Controller\\CitaController::getCitas'], [], [['text', '/citas']], [], []],
    'get_especialidades' => [[], ['_controller' => 'App\\Controller\\EspecialidadController::getEspecialidades'], [], [['text', '/especialidades']], [], []],
    'get_especialidad' => [['id'], ['_controller' => 'App\\Controller\\EspecialidadController::getEspecialidad'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/especialidades']], [], []],
    'add_especialidad' => [[], ['_controller' => 'App\\Controller\\EspecialidadController::addEspecialidad'], [], [['text', '/especialidades']], [], []],
    'borrar_especialidad' => [['id'], ['_controller' => 'App\\Controller\\EspecialidadController::borrarEspecialidad'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/especialidades']], [], []],
    'get_medicos' => [[], ['_controller' => 'App\\Controller\\MedicoController::getMedicos'], [], [['text', '/medicos']], [], []],
    'get_otros' => [[], ['_controller' => 'App\\Controller\\OtroController::getOtros'], [], [['text', '/otros']], [], []],
    'get_salas' => [[], ['_controller' => 'App\\Controller\\SalaController::getSalas'], [], [['text', '/salas']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\UsuarioController::login'], [], [['text', '/usuarios/login']], [], []],
    'registro' => [[], ['_controller' => 'App\\Controller\\UsuarioController::registrar'], [], [['text', '/usuarios/registro']], [], []],
    'get_usuario' => [[], ['_controller' => 'App\\Controller\\UsuarioController::getUsuario'], [], [['text', '/usuarios']], [], []],
    'actualizar_usuario' => [[], ['_controller' => 'App\\Controller\\UsuarioController::actualizarUsuario'], [], [['text', '/usuarios']], [], []],
    'eliminar_usuario' => [[], ['_controller' => 'App\\Controller\\UsuarioController::borrarUsuario'], [], [['text', '/usuarios']], [], []],
];
