<?php

namespace ContainerD5w5KGi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VT95Pc_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VT95Pc.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VT95Pc.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CitaController::borrarCita' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'App\\Controller\\CitaController::crearCita' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'App\\Controller\\CitaController::getCitas' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'App\\Controller\\UsuarioController::actualizarUsuario' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'App\\Controller\\UsuarioController::borrarUsuario' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'App\\Controller\\UsuarioController::getUsuario' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CitaController:borrarCita' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'App\\Controller\\CitaController:crearCita' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'App\\Controller\\CitaController:getCitas' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'App\\Controller\\UsuarioController:actualizarUsuario' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'App\\Controller\\UsuarioController:borrarUsuario' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'App\\Controller\\UsuarioController:getUsuario' => ['privates', '.service_locator.mWNDzqt', 'get_ServiceLocator_MWNDzqtService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CitaController::borrarCita' => '?',
            'App\\Controller\\CitaController::crearCita' => '?',
            'App\\Controller\\CitaController::getCitas' => '?',
            'App\\Controller\\UsuarioController::actualizarUsuario' => '?',
            'App\\Controller\\UsuarioController::borrarUsuario' => '?',
            'App\\Controller\\UsuarioController::getUsuario' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CitaController:borrarCita' => '?',
            'App\\Controller\\CitaController:crearCita' => '?',
            'App\\Controller\\CitaController:getCitas' => '?',
            'App\\Controller\\UsuarioController:actualizarUsuario' => '?',
            'App\\Controller\\UsuarioController:borrarUsuario' => '?',
            'App\\Controller\\UsuarioController:getUsuario' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
